### ISSUE TITLE
Is dropdown text too small in Windows?

### ISSUE THREAD

**Issue by kidcompassion** [TheTyee/design-article.thetyee.ca#110]
![uploads/212a8ab0-bae9-48bb-ba17-9be58e3d00a5/Screen Shot 2016-04-08 at 3.08.29 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F212a8ab0-bae9-48bb-ba17-9be58e3d00a5%2FScreen+Shot+2016-04-08+at+3.08.29+PM.png)

**Comment by alexgreen** [comment]
Looks like it's exactly the same size as on OSX chrome, iOS chrome, and android chrome. But yes I'd say it's too small in all cases. Should be at least the same size as the author bio teaser, and probably as large as the article body text, otherwise touchscreen people will have a hard time aiming their clicks.
