### ISSUE TITLE
Browser testing

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#168]
https://litmus.com/pages/

**Comment by MrBryan** [comment]
I ran a few tests on litmus pages https://litmus.com/pages/29387153 https://litmus.com/pages/29386847

But more telling is the interactive testing in browserstack (we have one license/seat) which has real devices connected as well as my own VM's and devices. And I have to say I'm amazed how smoothly it's running so kudos for all the testing done along the way.

There are a few little things i have noted that I don't think should stop launch. And worth noting is that it's unusable on IE8 but I don't think we were aiming to go back that far anyways.

If anyone has time to try pages out, I have been regularly previewing all of the recent stories linked from preview.thetyee.ca so you can browse around them all with your devices.

I'm going to focus on the testing on the site itself (not github /  gh-pages) from this point rather than the workflow of going back and forth between branches and cms systems  / jekyl/bric but you can see I have published a branch bc-bricmod where whatever files that could be straight-up added as includes are in there with the jekyl swapped for php langauge and gradually I will find a way to get some more bric templates into that branch.

**Comment by phillipadsmith** [comment]
Is there a next action on this ticket, or may I close it?

**Comment by MrBryan** [comment]
I think it's closable, we're doing lots of testing as we go

**Comment by alexgreen** [comment]
there are a couple issues on Android, one or two that Michelle reported
