### ISSUE TITLE
Presents footer text

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#198]
Right now, present stories get some boilerplate added about being paid content. This needs to carry over.

**Comment by MrBryan** [comment]
Added the same include from before, wrapped in `<small><em>` for now... should we look more closely / alex?

http://preview.thetyee.ca/Presents/2016/06/09/Start-Farmers-Market/index.html

**Comment by alexgreen** [comment]
In ye olden days we had already agreed to put this text in a fact-box. It's been coded in the repo since early June and it even adapts to the placement of a Presents Series box:

http://thetyee.github.io/design-article.thetyee.ca/presents
http://thetyee.github.io/design-article.thetyee.ca/presents-series

**Comment by MrBryan** [comment]
Cool. Moved it there
