### ISSUE TITLE
Bio issues on small screens

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#212]
> 1. On Condon's transit story, the bio gets cut off halfway through (ending at "winner of the ON/OFF..."). See attached. This seems to be true for other stories... when the bio is too long, it just gets lopped off rather than link out or anything. Is there a solution for this?
>    http://preview.thetyee.ca/Opinion/2016/05/24/UBC-Let-Students-Live-on-Campus/

@alexgreen This appears to be a problem on the GitHub repo too? I thought this was solved by hiding the bio on small screens?

**Comment by alexgreen** [comment]
There's already a solution, but it still needs to be carried over into bric.

See here:
http://thetyee.github.io/design-article.thetyee.ca/presents-series
`<a href="#" class="author-more">... read more</a>`

**Comment by phillipadsmith** [comment]
That doesn't appear to be a solution to me:

<img width="385" alt="margolese_prize_winner_bing_thom_on_the_art_of_placemaking___the_tyee" src="https://cloud.githubusercontent.com/assets/34128/16504845/d015e990-3ece-11e6-9db4-6740e8257fe5.png">

From memory, I believe that bios were going to disappear on small screens, not get oddly truncated?

**Comment by alexgreen** [comment]
Yes, you're right. For some reason only the "read more" disappears. Lemm see, should be a quick fix.

**Comment by alexgreen** [comment]
This declaration got inserted at line 3324 of the stylesheet and it overrides the prior css, so I've commented it out now. LMK if this line has a purpose.

```
    /* ARTICLE HEADER ========*/
    .author-info__bio{
      display: block;
    }
```

**Comment by phillipadsmith** [comment]
> Yes, you're right. For some reason only the "read more" disappears. Lemm see, should be a quick fix.

Related issue?

<img width="827" alt="school_board__sell_your_mall__that_s_no_way_to_fund_education___the_tyee" src="https://cloud.githubusercontent.com/assets/34128/16629568/0fe21cc4-436b-11e6-9428-878a160f8963.png">

**Comment by alexgreen** [comment]
Relevant, but not related. This is actually an issue on big screens rather than small ones.

The design assumes that bios will always be more than two lines long (as all our prior discussion has been about how to truncate all the super-long bios that staff have). So it always gives 2 lines of space and then provides a "read more" link to the author's bio page readers who want to see the full bio.

However it now appears that authors have incredibly short bios. (Jeremy Nutall's is also a one-liner: http://preview.thetyee.ca/News/2016/07/04/Temporary-Foreign-Worker-Review/index.html ) Is this really the case? Are Tyee authors actually suffering from a short-bio affliction, or is this just specific to the preview site? 

When I click through to Jeremy's bio page I see that it is in fact 3 paragraphs long. So it seems like there's an extremely truncated teaser bio that's being injected from somewhere. 

I think it would be great if the bio teasers were longer, but now I've adjusted the html and CSS so that the "read more" link should always align with the teaser baseline. cb3e4fde255af2b97d4502bf9cbc8ca0dda7295e

Here's some examples of how looks:

![screen shot 2016-07-09 at 2 36 45 am](https://cloud.githubusercontent.com/assets/151099/16707314/0a98d02c-457e-11e6-8f88-9d027ad25835.png)

---

![screen shot 2016-07-09 at 2 35 57 am](https://cloud.githubusercontent.com/assets/151099/16707315/0a998094-457e-11e6-9414-3ca328ae6342.png)

**Comment by alexgreen** [comment]
Sound good?

**Comment by phillipadsmith** [comment]
> I think it would be great if the bio teasers were longer, but now I've adjusted the html and CSS so that the "read more" link should always align with the teaser baseline. cb3e4fd

Looks good, yes.

To the question of bios, there are two kinds of bios for each contributor:
1. The long bio used on their bio page (updated rarely)
2. The short bio used on the article page, which is actually re-written for almost every article.

I don't know why this is done, editorially, but it is the way things are done.

@MrBryan can you merge this in?

**Comment by MrBryan** [comment]
Is merged already... CLOSE!

**Comment by MrBryan** [comment]
![image](https://cloud.githubusercontent.com/assets/1721891/16747181/dfc44182-478b-11e6-9829-e5faf7f31d0f.png)
