### ISSUE TITLE
Related-story blocks should be distributed throughout story

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#221]
Often (always?) it seems that the related-story blocks all get clumped together at the top of a story. This is much to repetitive, as here: http://preview.thetyee.ca/News/2016/06/22/BC-Ban-Big-Bucks/

We had decided to distribute them throughout the story. Is that possible?
If not, then we should look at combining them into one block, otherwise we're just training readers to ignore them. (This would require some redesigning, so if we need to go this way then I think we should just limit the related-story blocks to 1 or 2 per article for now.)

**Comment by phillipadsmith** [comment]
> We had decided to distribute them throughout the story. Is that possible?

A question for Bryan. I think it's a bit tricky because there could be a bunch of other stuff in the sidebar.

> If not, then we should look at combining them into one block, otherwise we're just training readers to ignore them.

Kinda' agree on this point.

>  (This would require some redesigning, so if we need to go this way then I think we should just limit the related-story blocks to 1 or 2 per article for now.)

I think we should definitely limit it to one or two on older stories. Perhaps even just one. It's just related content, not the "meat" per se.

**Comment by alexgreen** [comment]
> I think we should definitely limit it to one or two on older stories. Perhaps even just one. It's just related content, not the "meat" per se.

—music to my ears! If they can't be separated then let's limit it to just 1 block.

@MrBryan , can we control where it goes? It would be great if it didn't appear before the more important content (such as fact-boxes).

Personally I do like to see related headlines so I can read up on the history/context of story. It would be great to expose more of them, but let's save that challenge for after the launch.

**Comment by phillipadsmith** [comment]
> @MrBryan , can we control where it goes? It would be great if it didn't appear before the more important content (such as fact-boxes).

My vote would be to leave it at the top for launch, then adjust if necessary.

> Personally I do like to see related headlines so I can read up on the history/context of story. It would be great to expose more of them, but let's save that challenge for after the launch.

👍

**Comment by MrBryan** [comment]
The editors can now create individual "related story" items and place them wherever they like in the element flow.  But for older stories, they will spit out in a block near the top since they are one "related stories" element.

What I can do is try to divide the story length in paragraphs by the number of related story items in the old blocks and distribute them a bit better that way. I'll test out a bit how that would work/look

**Comment by phillipadsmith** [comment]
> What I can do is try to divide the story length in paragraphs by the number of related story items in the old blocks and distribute them a bit better that way. I'll test out a bit how that would work/look

I still think a single "related story" on old stories would actually be a fine / possibly preferable solution, as it would give the older stories a bit more whitespace / breathing room in that sidebar.

**Comment by MrBryan** [comment]
OK maybe we should verify with editors? All of those were thought through & selected so seems like a shame while I also see your point

**Comment by phillipadsmith** [comment]
> OK maybe we should verify with editors?

Sure. I've asked Robyn for her opinion.... 

>  All of those were thought through & selected so seems like a shame while I also see your point

The other option, I think Alex proposed, was to come up with a treatment for old stories that take into account a group of 3-5 stories.

Because of the new treatment -- where each story become a block with a photo -- it does tend to undermine the idea behind this new treatment (to give the occasional related story **more** prominence) and new stories will now run with 0-2 related stories, and only when there's a strong reason to relate one, which does support the idea of having fewer blocks in the sidebar.

Anyway, we'll see what Robyn says. :-)

**Comment by phillipadsmith** [comment]
> Anyway, we'll see what Robyn says. :-)

Robyn says "Fine to go with just one related story for re-launch."

We can always re-visit later.

**Comment by MrBryan** [comment]
Ok cool. One at beginning of story then ?

**Comment by MrBryan** [comment]
OK I have it set to just show one now in the template related_stories

**Comment by alexgreen** [comment]
I've created a new issue for future revisitation. #264
