### ISSUE TITLE
Square primary media?

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#232]
@alexgreen Thoughts on this: http://preview.thetyee.ca/Opinion/2016/01/04/Most-Hysterical-Election-BC/

**Comment by alexgreen** [comment]
This is a red herring. The image isn't actually square, it only appears to be because there's enormous white borders within the img itself. If it were actually a square img then it would fill the space properly.

So, it's a problem with this specific image (i.e. this image is cropped incorrectly, like a letter-boxed film) and the only (sane) way to fix it is to properly crop the image to its subject matter. :)

However, this makes me wonder whether there may at one time (or even now?) have been a Tyee photo editor who made such cropping a common practice. Have you seen this often?

**Comment by phillipadsmith** [comment]
> However, this makes me wonder whether there may at one time (or even now?) have been a Tyee photo editor who made such cropping a common practice. Have you seen this often?

Once in 100 stories -- so not a big issue.
