### ISSUE TITLE
Small, portrait orientation photo in aside does not hide on small screens

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#236]
http://preview.thetyee.ca/Culture/2016/01/13/Podcast-Overload/

<img width="385" alt="homeless_victoria_campers_won_t_budge___we_are_part_of_the_solution____the_tyee" src="https://cloud.githubusercontent.com/assets/34128/16547965/5d63eb42-4133-11e6-8bb3-05e4c6621d26.png">

(Looks great at the larger sizes, however!)

**Comment by MrBryan** [comment]
That's the normal behaviour -- the reason the other images disappear in the story is that they are related stories (not photos in the story).

Currently, that gap you showed does not occur, might be a css change since or the fact that only one related story is there

**Comment by phillipadsmith** [comment]
The issue still exists for me (I pasted the wrong story above):
http://preview.thetyee.ca/News/2016/01/12/Homeless-Victoria-Campers/

> That's the normal behaviour -- the reason the other images disappear in the story is that they are related stories (not photos in the story).

I guess that makes sense, and yet I would think they'd expand on small screens to fill the width...?

**Comment by alexgreen** [comment]
In fact they're supposed to disappear in views narrower than 500px, along with all other asides. See here: http://thetyee.github.io/design-article.thetyee.ca/library

This had been decided in consultation with editorial.

On that page it's only showing up because a display style property is hard-coded into the html:
`<aside class="aside " data-dev-object-descrip="01-molecules/blocks/aside" data-dev-status="IN-PROGRESS" style="display: block;">
`

@MrBryan can you remove the code that's injecting that style declaration so that the object can be styled normally from stylesheet?

However, I agree that it should actually remain visible in small views because the intention is for these images to be part of the article content. And in that case they should expand to fill the column. This would make them unlike any other aside, so I think the reasonable way to do this is probably to create a class extension of the .aside object or to make it into a new kind of extra-small figure (which would probably be more semantically correct). 

I can look into this.

**Comment by phillipadsmith** [comment]
> However, I agree that it should actually remain visible in small views because the intention is for these images to be part of the article content. And in that case they should expand to fill the column. This would make them unlike any other aside, so I think the reasonable way to do this is probably to create a class extension of the .aside object or to make it into a new kind of extra-small figure (which would probably be more semantically correct).

That would be great @alexgreen, thanks.

I'm still seeing it this morning (only for iPhone 5):

<img width="315" alt="screenshot_2016-07-11__11_36_am" src="https://cloud.githubusercontent.com/assets/34128/16742304/f57007bc-475b-11e6-9eb0-b67a81278062.png">

**Comment by MrBryan** [comment]
OK removed the inline style ... presently those will all disappear at mobile so Alex is looking into how to address that since they should be there

**Comment by alexgreen** [comment]
@MrBryan it appears that the persistence of these aside imgs _was_ actually intentional on my part (despite that fact editorial didn't think they were necessary). I had added this js script with a polyfill that implemented the :has Pseudo-Class from the upcoming CSS draft spec. Sorry, I forgot that I'd already done this! 

```
<!-- This implements the :has Pseudo-Class selector from editor's draft of the CSS Selectors Level 4 as described here: http://www.ericponto.com/blog/2015/01/10/has-pseudo-class-parent-selector/. Requires jquery, polyfill.js)-->
<script>
    Polyfill({
        selectors: [":has"]
    }).doMatched(rules => {
        rules.each(rule => {
            // just pass it into jQuery since it supports `:has`
            $(rule.getSelectors()).css(rule.getDeclaration())
        });
    });
</script>
```

When I originally added this script it worked. But for some reason it's no longer functioning, although it still appears in the page footer and the css declaration is still in the stylesheet. Any ideas?

**Comment by alexgreen** [comment]
I've styled these asides to fill the column in mobile views. 750dcc60ad84736b1c71f101c4ac5d33368f6fe9
So once the above polyfill is working this issue should be done.

**Comment by MrBryan** [comment]
I'm not sure why it's not working but since in our use case it can be accomplished by a single line of javascript on doc ready let's just do that -- it's tested and working and we can remove polyfill.js

$(".aside:has(> img)").css("display", "block");

1dc59fb

**Comment by MrBryan** [comment]
Pardon the multiple emails you got about this I cleaned up a mess of merges and redid some work. So I fixed this with  $(".aside:has(> img)").css("display", "block");
c407c9f00efd830eaadb31b2cf6e4e36e4cbc13a
This means probably we can get rid of polyfill since this covers our usage of it instead

**Comment by phillipadsmith** [comment]
> Pardon the multiple emails you got about this I cleaned up a mess of merges and redid some work. So I fixed this with $(".aside:has(> img)").css("display", "block");

Closed now?

**Comment by phillipadsmith** [comment]
Closing for now as it appears fixed to me.

**Comment by alexgreen** [comment]
> I fixed this with $(".aside:has(> img)").css("display", "block");

That will only work as a very temporary fix because it's a hack that only works for this one specific case, it makes the css very misleading to read and it doesn't produce the :has functionality which is incredibly useful for other cases as well. Can we just use the polyfill? Do you have an idea why the polyfill stopped working?

**Comment by alexgreen** [comment]
Ok. probably we should defer any polyfill debugging until after launch. So I'll comment it in the CSS and create a separate issue for it.

**Comment by MrBryan** [comment]
When we do take it up, I can easily detect in bric if there is an image present and pass on a class. Much simpler. I don't think we should be using any of these hacks / not yet arrived specs

**Comment by alexgreen** [comment]
It would be good to keep as little in bric as possible, because that creates a barrier to transparency and a bottleneck in the workflow. But yes, probably single lines of js that are commented within the css file could be a more reliable way go for these uncommon cases.

**Comment by alexgreen** [comment]
@MrBryan so that line of js will get parsed to select any .aside that contains a child img? It's basically identical to the syntax in the css draft spec.

**Comment by MrBryan** [comment]
yes what the js polyfill does is the same thing, exploits the fact that jquery has acknowledged the spec (where browsers haven't).  So it uses the same targetting pattern as the CSS since jQuery devs are ahead of the curve and aiming to be compatible.  Just this is a specific target rather than capturing all
