### ISSUE TITLE
Position of dateline and contributor name: intentional? 

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#244]
I'm confused about this:
<img width="319" alt="responsive_layouts_from_http___preview_thetyee_ca_opinion_2016_07_01_northern-gateway-decision_" src="https://cloud.githubusercontent.com/assets/34128/16628905/7c6079c0-4368-11e6-953c-0a73cd241a7f.png">

**Comment by alexgreen** [comment]
That's because padding-left is applied to the author-info__text to create space between text and author photo. But to accommodate cases where no author photo appears I've now replaced that padding-left with a margin-right on the photo. That way the gap will collapse if there's no photo present and then the text will align flush left, as in the photo below. 

However, there's one more problem.
On this particular page of the preview site (but not on other preview pages) something is injecting an inline negative margin which pulls the date out of alignment:
`<span style="margin-left:-4px;" class="author-info__date">`

@MrBryan why is this negative margin being injected? Can you remove it? If not, please apply it within the css so that it can be styled.

![screen shot 2016-07-09 at 1 08 27 am](https://cloud.githubusercontent.com/assets/151099/16706926/c861484c-4573-11e6-8433-25b3bb75731b.png)

**Comment by MrBryan** [comment]
That 4px was a fix for in bric there is a space between the comma and author that I couldn't figure out any other way.  I added it to css instead for over a breakpoint so that it doesn't mess up when it's on its own line like that

cfa1eaa

**Comment by MrBryan** [comment]
Here's with fixed alex + my css changes (others have to be repreviewed because the 4px was inline originally for testing)

**Comment by MrBryan** [comment]
http://preview.thetyee.ca/Opinion/2016/07/01/Northern-Gateway-Decision/index.html

**Comment by phillipadsmith** [comment]
> Here's with fixed alex + my css changes (others have to be repreviewed because the 4px was inline originally for testing)

Looks great, thanks.
