### ISSUE TITLE
Styling of homepage (interim?) nav block is not consistent with article pages

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#277]
http://preview.thetyee.ca/

I think this is pretty important, because the nav bar is our ONLY point of visual continuity across the whole site right now. We're already courting chaos by launching article pages that diverge dramatically in style from the listview pages,  so I would say that maintaining a consistent nav is absolutely critical for onboarding readers to this new design. Otherwise it will just feel like a random patchwork.

**(1) fonts in homepage (interim?) nav block are incorrect.** 
Currently they're Lucida and they should be Source Sans Pro. The following changes to nav-style-sp.css should fix it:

```
#header a {
    font-family: 'Source Sans Pro', sans-serif;
    font-style: normal;
    color: #555;
    font-weight: bold;
    font-size: 14.4px;
    text-transform: uppercase;
    letter-spacing: .04em;
}

```

**(2) Nav bar buttons are different and appear in a different arrangement**
Join button is wrong colour and has no icon.
Newsletter button is in wrong position.
Latest Stories is missing.
Active nav buttons should not have any background colour.

**Comment by MrBryan** [comment]
We don't want to spend much more time on this, we had done this as a short term thing so that people wouldn't get bumped to a non-responsive site for legacy articles but we will do a better job as part of the rest of the site later.  That said those are some easy wins but I'm quite sure everyone at the office agreed it will not be a launch blocker

**Comment by alexgreen** [comment]
> I'm quite sure everyone at the office agreed it will not be a launch blocker

@robynleighsmith From the point of view of user experience and reader credibility launching with the nav in this state of inconsistency would be a very bad idea. Not sure I can stress this enough.

**Comment by robynleighsmith** [comment]
@alexgreen @phillipadsmith @MrBryan Just seeing this now. The homepage preview that Alex posts at the top of the page does look different than a previous version I've seen. The nav is different. What happened?

**Comment by robynleighsmith** [comment]
How long would it take to fix this?

**Comment by alexgreen** [comment]
@MrBryan when you say

> we had done this as a short term thing so that people wouldn't get bumped to a non-responsive site for legacy articles

are you talking about **_listview_** pages? According to all our work during the past few weeks all legacy article will be rendered according to the new article templates, correct?

**Comment by MrBryan** [comment]
Nothing happened here -- that is the same nav we have had on the "interim" pages all along, I could dig it up where we chatted about in basecamp somewhere and Michelle had weighed in on it already too and given some revisions which we applied a few weeks ago.  To get it looking like much closer to the new article preview nav we would have to start adding new libraries etc, for instance source sans is not a web font so we're adding google fonts, and all of those changed locations of buttons were for practical reasons with having adequate space when shoe-horning the appearance onto the old site layout.  We can chat more about it tomorrow a.m

**Comment by MrBryan** [comment]
`are you talking about listview pages? According to all our work during the past few weeks all legacy article will be rendered according to the new article templates, correct?`

Yes sorry i meant listings and home page etc

**Comment by alexgreen** [comment]
Is it that difficult to load a font for a listview page in this stack? Readers will need to load it anyway in order to read the articles.

**Comment by alexgreen** [comment]
> all of those changed locations of buttons were for practical reasons with having adequate space

If the Newsletter button was on the correct side of the nav then there would be enough room for the Latest Stories button. The breakpoint to collapse the nav would need to be only _slightly_ wider than it is now.

**Comment by MrBryan** [comment]
If the font were the only thing it would be not too bad presumably but the latest stories in the existing site is a whole other can of worms that we are intentionally not opening. Let's focus energy on anything potentially left on the actual redesign part pre-launch

**Comment by alexgreen** [comment]
ok, if the latest stories is problematic then let's leave that out from the interim pages. So you've looked the code for this object and decided that it's unworkable and requires rebuilding? I haven't gone into it, but it does seem complicated and unpredictable.

**Comment by phillipadsmith** [comment]
Just weighing in here to say that A) I've removed the launch blocking label because this interim navigation on non-article pages was approved by Tyee staff weeks (if not months) ago, and B) confirming that we're all on the same page that it needs improvement, and yet was a best-effort way to move toward a fully-responsive site.

> How long would it take to fix this?

To rebuild the interim navigation would take a week to two weeks with testing across platforms and figuring out issues to do with missing libraries on the interim site. We've evaluated that option and decided it is not worth the investment given that those listing pages and the front page are on the list to re-design in the coming months.

I understand Alex's concern, and yet don't feel that this should be a surprise to anyone because it's been in place for months and -- frankly -- is quite consistent in mobile views (admittedly, not perfect, but not wildly inconsistent):

<img width="314" alt="iphone_5s_-_iphone_5s___ios_9_3__13e230_" src="https://cloud.githubusercontent.com/assets/34128/16793620/2d8e8a70-4887-11e6-801c-995449808eb4.png">
<img width="317" alt="iphone_5s_-_iphone_5s___ios_9_3__13e230_" src="https://cloud.githubusercontent.com/assets/34128/16793630/438ed23a-4887-11e6-8b8a-a070454c378c.png">
<img width="320" alt="screenshot_2016-07-12__11_21_pm" src="https://cloud.githubusercontent.com/assets/34128/16793657/72bbba50-4887-11e6-8844-e6462a3b876e.png">
<img width="318" alt="screenshot_2016-07-12__11_22_pm" src="https://cloud.githubusercontent.com/assets/34128/16793664/7d78ee86-4887-11e6-8b9e-9da9adc4d228.png">

And the reason we made this decision is because the analytics tell us that the majority of traffic arrives and leaves from article pages (>80%) and does not visit other pages, driven by e-mail newsletters and social sharing. The percentage of traffic that moves from article pages to list view pages or the front page is comparatively small. 

Hope that helps. Let's get these article pages launched and use our energy to circle back and do the real work of redesigning the balance of the site ASAP. :-)

Onward!

**Comment by alexgreen** [comment]
Is there some way we can at least use the correct font?

**Comment by alexgreen** [comment]
Is it really impossible to add the css declaration I posted at the top of this thread to correct the font issue? According to my browser this font is already being loaded, and it's required for the article pages anyway.

The submenus can be handled with one additional declaration. Here they are with a couple minor revisions.

```
#header a {
    font-family: 'Source Sans Pro', 'Lucida Grande', 'Lucida Sans', Verdana, sans-serif;
    font-style: normal;
    color: #555;
    font-weight: bold;
    font-size: 14.4px;
    text-transform: uppercase;
    letter-spacing: .04em;
}

#header .dropdown-wrap a {
    font-weight: normal;
    font-size: 14.4px;
    text-transform: none;
    letter-spacing: 0;
}
```

**Comment by MrBryan** [comment]
it gets loaded by calling to google fonts does it not? Source is not a webfont / one included in any OS,  so I believe it won't work unless that is included too

**Comment by alexgreen** [comment]
Source does show for me on that page in chrome even with the cache disabled, but yes if it's really only being loaded on some pages and not others then it should probably get added universally.
