### ISSUE TITLE
Huge gap under embedded Tweet / beside series box

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#279]
http://preview.thetyee.ca/News/2016/07/02/Kingsgate-Mall-VSB/
<img width="1018" alt="selling_kingsgate_mall_helps_bc_liberal_donors__not_schools__blogger___the_tyee" src="https://cloud.githubusercontent.com/assets/34128/16793085/04fd8236-4883-11e6-892a-50447bae5e83.png">

**Comment by alexgreen** [comment]
Yeah, I noticed other weird behaviour around the twitter embed and I'm pretty sure it's either because  a tag isn't closed, or there's a tag being closed prematurely.

**Comment by phillipadsmith** [comment]
> Yeah, I noticed other weird behaviour around the twitter embed and I'm pretty sure it's either because a tag isn't closed, or there's a tag being closed prematurely.

Because of the Twitter widget, or because of something else?

**Comment by alexgreen** [comment]
not sure. just guessing based on how it behaves. I'll have to look at the markup when I'm done my current task.

**Comment by alexgreen** [comment]
Yup, i was right. you can see here that there's an orphan `</div>` right after the twitter block and it prematurely closes the article__body column's container div. This twitter object doesn't exist in the github repo so I can't really debug where that `</div>` is coming from.

![screen shot 2016-07-13 at 1 49 57 am](https://cloud.githubusercontent.com/assets/151099/16797472/905b0b3c-489c-11e6-9c4d-ce3b01dac789.png)

That `</div>` is causing some alignment problems and it's also causing the gap because the container that it closes has a clearfix class.

Like all media objects the twitter widget should be sitting inside a figure.html.

**Comment by MrBryan** [comment]
Thanks for catching that - i twas an error in the logic of when to wrap the embedded media in the responsive container -- closing div in the wrong spot.  Fixed

**Comment by phillipadsmith** [comment]
> Yup, i was right. you can see here that there's an orphan </div> right after the twitter block and it prematurely closes the article__body column's container div. This twitter object doesn't exist in the github repo so I can't really debug where that </div> is coming from.

We can easily embed a Twitter widget in the repo. 

cc @MrBryan
