### ISSUE TITLE
Series box + half-page ad + Safari = problem

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#294]
Here's one for you, @alexgreen:

<img width="1111" alt="ten_things_learned_living_off-grid_in_canada___the_tyee" src="https://cloud.githubusercontent.com/assets/34128/16819106/c0dcc5e4-48ff-11e6-8bfa-638f33b652cc.png">

**Comment by alexgreen** [comment]
link?

**Comment by alexgreen** [comment]
That is almost certainly caused by the presence of a video in the featured-media section.

**Comment by phillipadsmith** [comment]
Link: http://preview.thetyee.ca/Culture/2014/12/29/Off-Grid-In-Canada/index.html

**Comment by alexgreen** [comment]
odd. I can't get safari to load any img assets on that page, although it does load assets from other preview pages.

**Comment by alexgreen** [comment]
I pretty sure the problem is a discrepancy between safari and chrome in terms of how they treat negative margins.

We currently have js applying a negative margin to section.featured-media to close the gap when the media object is shorter that the featured ad. 

In chrome it seems that the height and properties of objects within a container will override the container's negative margin. So the featured ad and its own margin overrides this negative margin of the containing section.featured-media, thus keeping the content asides below the ad while only the body text moves up to close the gap. 

But in Safari it seems that a negative margin on a container will override all the objects it contains. So section.featured-media overrides the height of all its contained elements and thus the content aside gets pulled up along with the text column and collides with the ad-block .

In fact I'm pretty surprised that this actually works in chrome even.

![screen shot 2016-07-13 at 4 38 04 pm](https://cloud.githubusercontent.com/assets/151099/16823547/027b1ff4-491a-11e6-89f5-733a3299dc72.png)

![screen shot 2016-07-13 at 4 38 40 pm](https://cloud.githubusercontent.com/assets/151099/16823554/0fded4ec-491a-11e6-85c7-d526248192ad.png)

**Comment by phillipadsmith** [comment]
> I pretty sure the problem is a discrepancy between safari and chrome in terms of how they treat negative margins.

Well deduced. Any proposed solutions?

**Comment by alexgreen** [comment]
I need to do browser testing to see which browser is the outlier. But it appears that our browserstack login has changed.

**Comment by phillipadsmith** [comment]
> I need to do browser testing to see which browser is the outlier. But it appears that our browserstack login has changed.

Ack. I recall @MrBryan saying he reset it.

**Comment by MrBryan** [comment]
Sorry yes that was me looks like you got it.  Maybe just some position relative + top px would be more browser compatible

**Comment by MrBryan** [comment]
fixed https://github.com/TheTyee/design-article.thetyee.ca/commit/95cf0ee6afe7d3f382a6ae04483325bf8cf8f2b5, https://github.com/TheTyee/design-article.thetyee.ca/commit/ae59714645cbb67d6649275ddef15479ea6c3c11, https://github.com/TheTyee/design-article.thetyee.ca/commit/4ed6cae4185b3c7a299fdade7c6eaff5f467ca5c
