### ISSUE TITLE
Add items to "More" nav dropdown

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#38]
For the MORE section, we should be looking at everything that's currently missing from the footer section (screenshot attached.)  For sure we need:

Advertise
About Us
Contact
Contributors
Master Classes
Privacy Policy
Barometer poll section?
Tyee Presents section?

I also think some redundancy from sidebar nav items isn't a bad idea, so maybe:

Support The Tyee
Newsletter

Questions: 
do we want 'submissions,' 'jobs,' 'Tyee News,' 'publications,' 'weekly archives'?

**Comment by kidcompassion** [comment]
<img width="1205" alt="screen shot 2016-03-09 at 1 20 06 pm" src="https://cloud.githubusercontent.com/assets/1507827/13649196/acca7d80-e5f9-11e5-9808-5dbe6384a8f4.png">
Took everything mentioned here and loaded it under "More" in branch sp-based-off-ag-atomic, commit fa635d5e77d697d588a2e7c1a343ba93efaa0df8. Not closing, since there are still changes to come.
