### ISSUE TITLE
add barometer poll block

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#39]
missing from current github version: the barometer poll at the bottom.  Should be in the stack with the builder and subscribe boxes.  Can't remember order we agreed on, but it's missing from that footer area.

**Comment by kidcompassion** [comment]
Adds first pass at this in branch sp-based-off-ag-atomic, commit 727a6b2986b8af33601dc31ea9a23ae258bf00cd. 

@alexgreen, if anything I'm doing is something you want me to keep my grubby paws off of, just let me know. Since I have some time today, I'm just barrelling through as many issues as possible.

**Comment by alexgreen** [comment]
In Seoul I'm 17 hrs ahead of Vancouver, so bear in mind that I will rarely read your messages on the same day you post them.
