### ISSUE TITLE
Search input improvements?

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#49]
I'm not totally in love with how the search input shows up in a drop down -- it almost feels too far away from the magnifying glass. Perhaps something to tackle down the road, yet wanted to put a bookmark on it. 

My very quickly considered proposal would be to show the input just to the left of the icon, thus hiding the menu to the left while the search input is active.

At minimum, the focus/cursor should be in the input once the magnifying glass is clicked.

**Comment by kidcompassion** [comment]
Minimum achievement unlocked! Click the search button and start typing, the focus automagically switches.

**Comment by phillipadsmith** [comment]
:100:

**Comment by alexgreen** [comment]
Can the focus switch immediately upon drop-down expansion, prior to typing? 
There needs to be a visual cue that focus has switch and people can type right away, otherwise I think most will assume they still need to click on the input field to manually switch focus.

(Obviously this is a low-priority fine-tuning task now.)

**Comment by phillipadsmith** [comment]
@kidcompassion Working on this, or can I re-assign?

**Comment by kidcompassion** [comment]
@phillipadsmith Nope, re-assign away! :D Thank you!

**Comment by phillipadsmith** [comment]
> Nope, re-assign away! :D Thank you!

👍

**Comment by phillipadsmith** [comment]
@MrBryan You got this one, yes? :-)

**Comment by MrBryan** [comment]
cfbdbff28f37f0c147933363ac577b2d61ad2b3d
