### ISSUE TITLE
AJAX request to API

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#57]
Noticing that the API is getting called with 50 stories as the parameter, e.g.:
http://api.thetyee.ca/v1/latest/50

... which results in a long wait time for that request to come back.

I'd propose we A) reduce the number requested to 10 or so, and B) put some caching on that API to speed up requests that don't change much, and C) add pagination to the API to enable an offset parameter.

I'll put B and C on my plate for other API-related work I've got scheduled.

**Comment by kidcompassion** [comment]
@phillipadsmith actually, I have since reworked this code! In my v1 I was hitting the API on every click, which I'm pretty sure is what was making it so slow; now I pull 50 stories once and load them into an array of story object, which I then sort through. For me, it now works way faster; if you have time, can you try the version in the develop branch and tell me if it resolves the lag for you too, or if it's still slow? Also, I can always reduce the number of stories (what kind of lunatic wants to scroll through 50 stories anyway?!)  which could also speed it up, as would using thumbnails.

If it is faster for you and you're cool with, my preference is to leave it as is before March 28, since I'd really like to get everything done on time, and I wouldn't be able to get this reworked and complete other tickets in time

**Comment by phillipadsmith** [comment]
@kidcompassion Howdy! I'll check out the 'develop' branch and see how it is. I was more looking at the size of the payload, which was about 3-4x larger for 50 stories than it is for say 10. Yet, happy to see this put this on the "later" list.
